### ISSUE TITLE
Option to forward both stdout and stderr to the same file (*.log)

### ISSUE THREAD

**Issue by glmars** [umputun/docker-logger#11]
For some users it will be very useful to have a single log file for a container.

**Comment by glmars** [comment]
Thank you for a such quick response! :wink: 

We are waiting for a new tag (`v1.2.0`) in https://hub.docker.com/r/umputun/docker-logger/tags and we are going to use new option in our project. :tada:

**Comment by umputun** [comment]
Looks like recent changes on dockerhub prevented my automatic build for a new tag. I had to change build configuration and recreate `v1.2.0`. Looks like it worked and the image created this time.

**Comment by glmars** [comment]
Great! Now I see `v1.2.0` on dockerhub :tada:! Thanks.
