### ISSUE TITLE
environment LOG_FILES=true single log file for service in swarm mode

### ISSUE THREAD

**Issue by jonny64** [umputun/docker-logger#8]
Hi! Thanks for radio-t and this great tool

Given I use environment LOG_FILES=true 
When I deploy logger and service using docker swarm
Then docker ps shows random names (for each deploy swarm starts a container with random postfix: new log file is created)
And I got a million of small log files
-rw-r--r-- 1 root root    502 Aug 28 11:20 citlk_prod_back.1.h9laxuf7hhuuw4yznoigua1sv.err
-rw-r--r-- 1 root root    502 Aug 27 16:31 citlk_prod_back.1.hqf074zou6m0qwbq1f1kjup84.err
-rw-r--r-- 1 root root    502 Aug 20 15:17 citlk_prod_back.1.jeea6umrmwbph7prkxqa2gihu.err
-rw-r--r-- 1 root root    502 Aug 27 17:35 citlk_prod_back.1.kbcf9mef0yzyxr092i40cteqp.err

I would like to log to single file with COMPOSE_PROJECT_NAME + service name as log file name
I cant't find any naming setting for swarm that can solve this
I would like to try fix this or find a workaround

- Do you use this tool in production?
- Do you have any clues how to get service name or compose project name from dockerEvent.Actor.Attributes here
https://github.com/umputun/docker-logger/blob/0d623a5126c503416343cc42e49265b0e48fe6df/app/discovery/events.go#L80
or any idea what should be done to have single service log file and rotation
?

**Comment by umputun** [comment]
the intended use case is to run a container on the host to collect logs from all other containers on the same host. Running under swarm was never the goal. Probably it should be possible to add support of labels to allow user-defined naming, but either way - such functionality is way outside of the scope.
